name: Auto Mail Report

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v3

      - name: 安装 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: pip install python-dotenv openpyxl

      - name: 运行脚本
        run: python mail_filter.py

      - name: 提交更新
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "auto update report" || echo "no changes"
          git push
